---

- name: (install) | check openjdk
  shell: dpkg -l | grep openjdk
  register: openjdk_installed
  ignore_errors: yes
  when: ansible_os_family == "Debian"


- name: (install) | add openjdk PPA
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "14"
    - openjdk_installed.rc != 0


- name: (install) | install openjdk
  apt:
    name: openjdk-8-jre
    state: present
    update_cache: yes
  when:
    - ansible_os_family == "Debian"
    - openjdk_installed.rc != 0


- name: (install) | check openjdk
  shell: rpm -qa | grep openjdk
  register: openjdk_installed
  ignore_errors: yes
  when: ansible_os_family == "RedHat"


- name: (install) | install openjdk
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - java-1.8.0-openjdk.x86_64
  when:
   - ansible_os_family == "RedHat"
   - openjdk_installed.rc != 0


- name: (install) | stop namenode services if running
  service:
    name: "{{item}}"
    state: stopped
  with_items:
    - hadoop-dfs-namenode.service
    - hadoop-yarn-resourcemanager.service
    - hadoop-yarn-proxyserver.service
    - hadoop-mr-jobhistory.service
  when: hadoop_namenode in hostvars[inventory_hostname]['ansible_all_ipv4_addresses']
  ignore_errors: yes


- name: (install) | stop secondarynamenode services if running
  service:
    name: "{{item}}"
    state: stopped
  with_items:
    - hadoop-dfs-secondarynamenode.service
  when: hadoop_secondarynamenode in hostvars[inventory_hostname]['ansible_all_ipv4_addresses']
  ignore_errors: yes


- name: (install) | stop datanode services if running
  service:
    name: "{{item}}"
    state: stopped
  with_items:
    - hadoop-dfs-datanode.service
    - hadoop-yarn-nodemanager.service
  ignore_errors: yes


- name: (install) | remove hadoop-core directory
  file:
    path: /usr/local/hadoop
    state: absent
  with_items:
    - /etc/hadoop
    - /var/log/hadoop
    - /var/run/hadoop
    - /usr/local/hadoop


- name: (install) | download hadoop-core package
  get_url:
    url: http://apache.stu.edu.tw/hadoop/common/hadoop-{{hadoop_version}}/hadoop-{{hadoop_version}}.tar.gz 
    dest: /tmp
    mode: 0644


- name: (install) | extract hadoop-core package into /usr/local/hadoop
  shell: tar -zxvf /tmp/hadoop-{{hadoop_version}}.tar.gz -C /usr/local


- name: (install) | extract hadoop-core package into /usr/local/hadoop
  shell: mv /usr/local/hadoop-{{hadoop_version}} /usr/local/hadoop


- name: (install) | remove package in /tmp
  file:
    path: /tmp/hadoop-{{hadoop_version}}.tar.gz
    state: absent

